import { CooperativeLetter, Inspector, ChecklistStyle } from './types';

export const DEFAULT_INSPECTORS_POOL: Omit<Inspector, 'id'>[] = [
  { name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ', email: 'chajai.tk2025@gmail.com' },
  { name: 'นายปรีดี ศรีเหมือนทอง', title: 'ผู้ตรวจสอบกิจการ', email: 'preedi.s@tk-account.com' },
  { name: 'นายเจษฎา พูลสุข', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ', email: 'jessada.p@tk-account.com' },
  { name: 'นางสาวปรางทิพย์ เอียดเหตุ', title: 'ผู้ตรวจสอบกิจการ', email: 'prangthip.e@tk-account.com' },
  { name: 'นายกิตติพิชญ์ ยอดเพชร', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ', email: 'kittipich.y@tk-account.com' },
];

export function get17Items(monthYear: string = 'มิถุนายน 2569'): string[] {
  return [
    'สมุดสรุปประจำวัน',
    `บัญชีแยกประเภท เดือน${monthYear} (ไฟล์)`,
    `งบทดลองรายเดือน เดือน${monthYear} (ไฟล์)`,
    `สลิปรับ – จ่าย เดือน${monthYear}`,
    `สรุปยอดคงเหลือหุ้น - หนี้ ณ วันที่ 30 ${monthYear} (ไฟล์)`,
    `ทะเบียนจ่ายเงินกู้ทุกประเภท เดือน${monthYear} (ไฟล์)`,
    `หนังสือสัญญาเงินกู้ทุกประเภท เดือน${monthYear}`,
    `รายงานชำระหนี้แบบพิเศษ (รายวันและชำระหักกลบหนี้) พร้อมใบเสร็จพิเศษ เดือน${monthYear}`,
    `งบหน้าเรียกเก็บเงินหรือหักส่งประจำเดือน พร้อมใบเสร็จ เดือน${monthYear}`,
    `สรุปยอดคงเหลือเงินรับฝากจากสมาชิกทุกประเภท ณ วันที่ 30 ${monthYear} (ไฟล์)`,
    `รายงานการฝาก – ถอนประจำวัน เดือน${monthYear}`,
    `สมุดคู่ฝากธนาคารทุกธนาคารและใบแจ้งยอดเงินฝากกระแสรายวันทุกธนาคารแสดงยอด ณ วันที่ 30 ${monthYear} (ไฟล์)`,
    `ทะเบียนจ่ายเช็คและต้นขั้วเช็คทุกธนาคาร เดือน${monthYear}`,
    'ระเบียบ ข้อบังคับ และประกาศอัตราดอกเบี้ยของสหกรณ์ฯ',
    `รายงานการประชุมคณะกรรมการประจำ เดือน${monthYear}`,
    `รายงานสมาชิกเข้าใหม่ – ลาออกประจำ เดือน${monthYear}`,
    'เอกสารอื่น ๆ ที่ผู้ตรวจสอบร้องขอ'
  ];
}

export function get20Items(monthYear: string = 'มิถุนายน 2569'): string[] {
  return [
    'สมุดสรุปประจำวัน',
    `บัญชีแยกประเภท เดือน${monthYear}`,
    `งบทดลองรายเดือน เดือน${monthYear}`,
    `สลิป รับ - จ่าย ตั้งแต่เดือน${monthYear}`,
    `สรุปยอดคงเหลือหุ้น - หนี้ ณ วันที่ 30 ${monthYear}`,
    'การ์ดหรือ Statement รายบุคคลหุ้น - หนี้',
    `ทะเบียนจ่ายเงินกู้ทุกประเภท เดือน${monthYear}`,
    `หนังสือสัญญาเงินกู้ทุกประเภท เดือน${monthYear}`,
    `รายงานชำระหนี้แบบพิเศษ (รายวันและชำระหักกลบหนี้) พร้อมใบเสร็จพิเศษ เดือน${monthYear}`,
    `งบหน้าเรียกเก็บเงินหรือหักส่งประจำเดือน พร้อมใบเสร็จ เดือน${monthYear}`,
    `สรุปยอดคงเหลือเงินรับฝากจากสมาชิกทุกประเภท ณ วันที่ 30 ${monthYear}`,
    `รายงานการฝาก - ถอนประจำวัน เดือน${monthYear}`,
    'การ์ดหรือ Statement เงินรับฝากรายบุคคล',
    'สมุดคู่ฝากธนาคารทุกธนาคารและใบแจ้งยอดเงินฝากกระแสรายวันทุกธนาคาร',
    'ทะเบียนจ่ายเช็คและต้นขั้วเช็คทุกธนาคาร',
    'ระเบียบ ข้อบังคับ และประกาศอัตราดอกเบี้ยของสหกรณ์ฯ',
    `รายงานการประชุมคณะกรรมการประจำเดือน เดือน${monthYear}`,
    'รายงานกระทบยอดเงินฝากธนาคาร',
    'สมาชิกเข้าใหม่ - ลาออก',
    'เอกสารอื่น ๆ ที่ผู้ตรวจสอบร้องขอ'
  ];
}

export const INITIAL_LETTERS: CooperativeLetter[] = [
  {
    id: 'ayutthaya-police',
    orgName: 'สหกรณ์ออมทรัพย์ตำรวจภูธรจังหวัดพระนครศรีอยุธยา จำกัด',
    letterDate: 'วันที่ 26 มิถุนายน 2569',
    recipient: 'ผู้จัดการ สหกรณ์ออมทรัพย์ตำรวจภูธรจังหวัดพระนครศรีอยุธยา จำกัด',
    meetingYear: '2569',
    repName: 'นางสาวเฉลิมรัตน์ ใจดี',
    fiscalYearEnd: '30 กันยายน 2569',
    inspectionMonth: 'มิถุนายน 2569',
    inspectionPeriod: '1 มิถุนายน 2569 – 30 มิถุนายน 2569',
    inspectionDatesText: '6 - 7 กรกฎาคม 2569',
    inspectors: [
      { id: '1', name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '2', name: 'นายเจษฎา พูลสุข', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ' },
      { id: '3', name: 'นายปรีดี ศรีเหมือนทอง', title: 'ผู้ตรวจสอบกิจการ' },
    ],
    checklistStyle: '17-items',
    checklistItems: get17Items('มิถุนายน 2569'),
    signeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    signeeTitle: 'ผู้ตรวจสอบกิจการ',
    logoType: 'standard'
  },
  {
    id: 'community-dev',
    orgName: 'สหกรณ์ออมทรัพย์พัฒนาองค์กรชุมชน จำกัด',
    letterDate: 'วันที่ 26 มิถุนายน 2569',
    recipient: 'ผู้จัดการ สหกรณ์ออมทรัพย์พัฒนาองค์กรชุมชน จำกัด',
    meetingYear: '2568',
    repName: 'นางสาวคณพิชญ์ ศรีสง่า',
    fiscalYearEnd: '30 กันยายน 2569',
    inspectionMonth: 'มิถุนายน 2569',
    inspectionPeriod: '1 มิถุนายน 2569 – 30 มิถุนายน 2569',
    inspectionDatesText: '8 - 9 กรกฎาคม 2569',
    inspectors: [
      { id: '1', name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '2', name: 'นางสาวปรางทิพย์ เอียดเหตุ', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '3', name: 'นายเจษฎา พูลสุข', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ' },
    ],
    checklistStyle: '17-items',
    checklistItems: get17Items('มิถุนายน 2569'),
    signeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    signeeTitle: 'ผู้ตรวจสอบกิจการ',
    logoType: 'standard'
  },
  {
    id: 'red-cross',
    orgName: 'สหกรณ์ออมทรัพย์สภากาชาดไทย จำกัด',
    letterDate: 'วันที่ 26 มิถุนายน 2569',
    recipient: 'ผู้จัดการ สหกรณ์ออมทรัพย์สภากาชาดไทย จำกัด',
    meetingYear: '2568',
    repName: 'นางสาวคณพิชญ์ ศรีสง่า',
    fiscalYearEnd: '30 กันยายน 2569',
    inspectionMonth: 'มิถุนายน 2569',
    inspectionPeriod: '1 มิถุนายน 2569 – 30 มิถุนายน 2569',
    inspectionDatesText: '12 กรกฎาคม 2569',
    inspectors: [
      { id: '1', name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '2', name: 'นายเจษฎา พูลสุข', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ' },
      { id: '3', name: 'นายปรีดี ศรีเหมือนทอง', title: 'ผู้ตรวจสอบกิจการ' },
    ],
    checklistStyle: '17-items',
    checklistItems: get17Items('มิถุนายน 2569'),
    signeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    signeeTitle: 'ผู้ตรวจสอบกิจการ',
    logoType: 'standard'
  },
  {
    id: 'naval-training',
    orgName: 'สหกรณ์ออมทรัพย์กองการฝึก กองเรือยุทธการ จำกัด',
    letterDate: 'วันที่ 26 มิถุนายน 2569',
    recipient: 'ผู้จัดการ สหกรณ์ออมทรัพย์กองการฝึกกองเรือยุทธการ จำกัด',
    meetingYear: '2567',
    repName: 'นางสาวคณพิชญ์ ศรีสง่า',
    fiscalYearEnd: '30 กันยายน 2569',
    inspectionMonth: 'มิถุนายน 2569',
    inspectionPeriod: '1 มิถุนายน 2569 – 30 มิถุนายน 2569',
    inspectionDatesText: '13 กรกฎาคม 2569',
    inspectors: [
      { id: '1', name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '2', name: 'นายเจษฎา พูลสุข', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ' },
      { id: '3', name: 'นายปรีดี ศรีเหมือนทอง', title: 'ผู้ตรวจสอบกิจการ' },
    ],
    checklistStyle: '20-items',
    checklistItems: get20Items('มิถุนายน 2569'),
    signeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    signeeTitle: 'หัวหน้าสายตรวจสอบ',
    logoType: 'standard'
  },
  {
    id: 'naval-ordnance',
    orgName: 'สหกรณ์ออมทรัพย์กรมสรรพาวุธทหารเรือ จำกัด',
    letterDate: 'วันที่ 26 มิถุนายน 2569',
    recipient: 'ผู้จัดการ สหกรณ์ออมทรัพย์กรมสรรพาวุธทหารเรือ จำกัด',
    meetingYear: '2568',
    repName: 'นางสาวคณพิชญ์ ศรีสง่า',
    fiscalYearEnd: '30 กันยายน 2569',
    inspectionMonth: 'มิถุนายน 2569',
    inspectionPeriod: '1 มิถุนายน 2569 – 30 มิถุนายน 2569',
    inspectionDatesText: '14 กรกฎาคม 2569',
    inspectors: [
      { id: '1', name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '2', name: 'นายปรีดี ศรีเหมือนทอง', title: 'ผู้ตรวจสอบกิจการ' },
    ],
    checklistStyle: '20-items',
    checklistItems: get20Items('มิถุนายน 2569'),
    signeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    signeeTitle: 'ผู้ตรวจสอบกิจการ',
    logoType: 'standard'
  },
  {
    id: 'mental-health',
    orgName: 'สหกรณ์ออมทรัพย์กรมสุขภาพจิต จำกัด',
    letterDate: 'วันที่ 26 มิถุนายน 2569',
    recipient: 'ผู้จัดการ สหกรณ์ออมทรัพย์กรมสุขภาพจิต จำกัด',
    meetingYear: '2568',
    repName: 'นางสาวคณพิชญ์ ศรีสง่า',
    fiscalYearEnd: '30 กันยายน 2569',
    inspectionMonth: 'มิถุนายน 2569',
    inspectionPeriod: '1 มิถุนายน 2569 – 30 มิถุนายน 2569',
    inspectionDatesText: '15 - 16 กรกฎาคม 2569',
    inspectors: [
      { id: '1', name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '2', name: 'นางสาวปรางทิพย์ เอียดเหตุ', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '3', name: 'นายเจษฎา พูลสุข', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ' },
    ],
    checklistStyle: '17-items',
    checklistItems: get17Items('มิถุนายน 2569'),
    signeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    signeeTitle: 'ผู้ตรวจสอบกิจการ',
    logoType: 'standard'
  },
  {
    id: 'pwa',
    orgName: 'สหกรณ์ออมทรัพย์การประปาส่วนภูมิภาค จำกัด',
    letterDate: 'วันที่ 26 มิถุนายน 2569',
    recipient: 'ผู้จัดการ สหกรณ์ออมทรัพย์การประปาส่วนภูมิภาค จำกัด',
    meetingYear: '2568',
    repName: 'นางสาวคณพิชญ์ ศรีสง่า',
    fiscalYearEnd: '30 ธันวาคม 2569',
    inspectionMonth: 'มิถุนายน 2569',
    inspectionPeriod: '1 มิถุนายน 2569 – 30 มิถุนายน 2569',
    inspectionDatesText: '19 - 21 กรกฎาคม 2569',
    inspectors: [
      { id: '1', name: 'นางสาวเฉลิมรัตน์ ใจดี', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '2', name: 'นายเจษฎา พูลสุข', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ' },
      { id: '3', name: 'นายปรีดี ศรีเหมือนทอง', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '4', name: 'นางสาวปรางทิพย์ เอียดเหตุ', title: 'ผู้ตรวจสอบกิจการ' },
      { id: '5', name: 'นายกิตติพิชญ์ ยอดเพชร', title: 'ผู้ช่วยผู้ตรวจสอบกิจการ' },
    ],
    checklistStyle: '17-items',
    checklistItems: get17Items('มิถุนายน 2569'),
    signeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    signeeTitle: 'ผู้ตรวจสอบกิจการ',
    logoType: 'standard'
  },
];

export const INITIAL_LEAVE_REQUESTS = [
  {
    id: 'leave-1',
    dateText: 'วันที่ 30 เดือน มิถุนายน พ.ศ. 2569',
    subject: 'ขออนุญาตลากิจ',
    recipient: 'ผู้จัดการ',
    employeeName: 'นางสาวเฉลิมรัตน์ ใจดี',
    employeeTitle: 'หัวหน้าสายตรวจสอบ',
    leaveType: 'personal' as const,
    reason: 'ไปงานกิจกรรมโรงเรียนบุตร',
    delegateName: 'นางสาวปรางทิพย์ เอียดเหตุ',
    hasLastLeave: false,
    lastLeaveType: '' as const,
    lastLeaveStart: '',
    lastLeaveEnd: '',
    lastLeaveDays: '',
    contactAddress: '',
    contactPhone: '062-8954792',
    delegateSignName: '',
    approvalStatus: 'approved' as const,
    approvalReason: '',
    stats: {
      sick: { taken: '-', current: '-', total: '-' },
      personal: { taken: '-', current: '1', total: '1' },
      vacation: { taken: '2', current: '-', total: '2' },
    },
    checkerName: '',
    approverName: 'นางสาวคณพิชญ์ ศรีสง่า',
    leaveCalendarDay: 27,
  }
];

